wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678061934.35966
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      - 37
      4: 3.9.16
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 50
dropout:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: adam
